# Generated by Django 5.0.1 on 2024-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="forbidden",
            field=models.BooleanField(
                default=False,
                help_text="можно ли размещать на этой клетке приз",
                verbose_name="заблокировано",
            ),
        ),
    ]
