# Generated by Django 5.0.1 on 2024-01-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_cell_forbidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="editable",
            field=models.BooleanField(
                default=True,
                help_text="можно ли поле редактировать",
                verbose_name="редактирование",
            ),
        ),
        migrations.AddField(
            model_name="prize",
            name="description",
            field=models.TextField(
                default="", help_text="описание приза", verbose_name="описание"
            ),
        ),
        migrations.AddField(
            model_name="prize",
            name="name",
            field=models.CharField(
                default="",
                help_text="название приза",
                max_length=24,
                verbose_name="название",
            ),
        ),
    ]
