# Generated by Django 5.0.1 on 2024-02-03 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_game_editable_prize_description_prize_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shots",
            old_name="quanity",
            new_name="quantity",
        ),
    ]
