# Generated by Django 5.0.1 on 2024-02-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_rename_quanity_shots_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="prize",
            field=models.OneToOneField(
                blank=True,
                help_text="приз, который находится в клетке",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cell",
                to="game.prize",
                verbose_name="приз",
            ),
        ),
    ]
