# Generated by Django 5.0.1 on 2024-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_alter_cell_prize"),
    ]

    operations = [
        migrations.AddField(
            model_name="shots",
            name="touched",
            field=models.BooleanField(
                default=False,
                help_text="Использовал ли пользователь хоть один выстрел в игре",
                verbose_name="тронутый",
            ),
        ),
    ]
